using EventHandler.Contracts;

namespace EventHandler.Agent.Sources;

/// <summary>
/// The developer's demo harness: emits a synthetic IncomingEventDto on an interval, so
/// running the Agent fires the mandatory E2E path (skeleton-plan.md §8). Unlike the other
/// stub sources, this one is fully functional — that's its entire purpose.
/// </summary>
public sealed class MockEventSource : IEventSource
{
    private readonly ILogger<MockEventSource> _logger;
    private readonly TimeSpan _interval;
    private CancellationTokenSource? _linkedCts;
    private Task? _loopTask;

    public string Name => "Mock";

    public MockEventSource(ILogger<MockEventSource> logger, IConfiguration configuration)
    {
        _logger = logger;
        var seconds = configuration.GetValue("Sources:Mock:IntervalSeconds", 15);
        _interval = TimeSpan.FromSeconds(seconds);
    }

    public Task StartAsync(IEventSink sink, CancellationToken ct)
    {
        _linkedCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
        _loopTask = RunAsync(sink, _linkedCts.Token);
        return Task.CompletedTask;
    }

    public async Task StopAsync(CancellationToken ct)
    {
        _linkedCts?.Cancel();
        if (_loopTask is not null)
        {
            try
            {
                await _loopTask;
            }
            catch (OperationCanceledException)
            {
                // Expected on shutdown.
            }
        }
    }

    private async Task RunAsync(IEventSink sink, CancellationToken ct)
    {
        var counter = 0;
        while (!ct.IsCancellationRequested)
        {
            counter++;
            var evt = new IncomingEventDto(
                SourceName: Name,
                SourceEventId: $"mock-{counter}",
                Title: $"Mock event #{counter}",
                Description: "Synthetic event generated by MockEventSource for the E2E demo path.",
                Location: "Demo Site",
                OccurredAt: DateTimeOffset.UtcNow,
                Severity: "Normal");

            _logger.LogInformation("MockEventSource publishing {SourceEventId}", evt.SourceEventId);

            try
            {
                await sink.PublishAsync(evt, ct);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "MockEventSource failed to publish {SourceEventId}", evt.SourceEventId);
            }

            try
            {
                await Task.Delay(_interval, ct);
            }
            catch (OperationCanceledException)
            {
                break;
            }
        }
    }
}
